### ISSUE TITLE
BUG: near state does not work from cron

### ISSUE THREAD

**Issue by gaia** [nearprotocol/stakewars#139]
trying to run `near state account.test` from cron. It works fine from the cmd line, but when placed under the user's own crontab as `/usr/bin/near state account.test`, i get 

```Using options: { networkId: 'default',
  nodeUrl: 'https://rpc.testnet.nearprotocol.com',
  contractName: undefined,
  walletUrl: 'https://wallet.testnet.nearprotocol.com',
  helperUrl: 'https://helper.testnet.nearprotocol.com',
  accountId: 'gaia.test',
  initialBalance: null }
Error:  { Error: [-32000] Server error: account gaia.test does not exist while viewing
    at JsonRpcProvider.sendJsonRpc (/usr/lib/node_modules/near-shell/node_modules/near-api-js/lib/providers/json-rpc-provider.js:113:27)
    at process._tickCallback (internal/process/next_tick.js:68:7) type: 'UntypedError' }```

**Expected behavior OR Outcome of test**
full output, as seen from CLI

**Specs (please complete the following information):**
 - Ubuntu 18.04.1
- Bare Metal
- i5-7500
- 24 GB
- 1.5TB

**Comment by jimmy3dita** [comment]
this is related to the wrong node environment. Try to use hardcode the walletUrl and helperUrl in the command itself:

`near state test --walletUrl https://wallet.betanet.nearprotocol.com --helperUrl https://helper.betanet.nearprotocol.com`

**Comment by gaia** [comment]
same

```
Using options: { walletUrl: 'https://wallet.betanet.nearprotocol.com',
  helperUrl: 'https://helper.betanet.nearprotocol.com',
  networkId: 'default',
  nodeUrl: 'https://rpc.testnet.nearprotocol.com',
  contractName: undefined,
  accountId: 'gaia.test',
  initialBalance: null }
Error:  { Error: [-32000] Server error: account gaia.test does not exist while viewing
    at JsonRpcProvider.sendJsonRpc (/usr/lib/node_modules/near-shell/node_modules/near-api-js/lib/providers/json-rpc-provider.js:113:27)
    at process._tickCallback (internal/process/next_tick.js:68:7) type: 'UntypedError' }
```

**Comment by jimmy3dita** [comment]
`near state test --walletUrl https://wallet.betanet.nearprotocol.com --helperUrl https://helper.betanet.nearprotocol.com --nodeUrl https://rpc.betanet.nearprotocol.com` should do the job

**Comment by gaia** [comment]
That did it! but the coloring codes go mixed in

```
Account gaia.test
{ amount:  [32m'3609605243867402846961456662' [39m,
  locked:  [32m'100583791315155543828524972383' [39m,
  code_hash:  [32m'11111111111111111111111111111111' [39m,
  storage_usage:  [33m510 [39m,
  storage_paid_at:  [33m0 [39m,
  block_height:  [33m3818145 [39m,
  block_hash:  [32m'JDbWXbcJZG6bJoSv2RC9GmBkMcytEzAzfcrqejPMJLop' [39m,
  formattedAmount:  [32m'3,609.605243867402846961456662' [39m }
```
