### ISSUE TITLE
[BUG] Unconfigured environment 'tatooine'

### ISSUE THREAD

**Issue by joesixpack** [nearprotocol/stakewars#46]
**Describe the bug or test**
near-shell doesn't understand tatooine env variable.

**How to Reproduce**
sudo  npm install -g near-shell
npx create-near-app nearstaking
cd nearstaking
export NODE_ENV=tatooine
near login

**Expected behavior OR Outcome of test**
j@j-desktop:~/nearstaking$ near login
[WARNING] Didn't find config at /home/j/nearstaking/src/config, using default shell config
/usr/local/lib/node_modules/near-shell/blank_project/src/config.js:43
                throw Error(`Unconfigured environment '${env}'. Can be configured in src/config.js.`);
                ^

Error: Unconfigured environment 'tatooine'. Can be configured in src/config.js.
    at getConfig (/usr/local/lib/node_modules/near-shell/blank_project/src/config.js:43:23)
    at getConfig (/usr/local/lib/node_modules/near-shell/get-config.js:11:72)
    at Object.<anonymous> (/usr/local/lib/node_modules/near-shell/bin/near:178:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)
    at internal/main/run_main_module.js:16:11
j@j-desktop:~/nearstaking$

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04.3
- CPU: 4  cores
- RAM: 4GB
- Disk space: 110GB

**Comment by janedegtiareva** [comment]
What version of near-shell are you using? This should not happen on latest version (0.14.2).

**Comment by joesixpack** [comment]
I pulled the latest from the repository.  Can't actually query for the version because the same error pops up.

**Comment by joesixpack** [comment]
Looks there's two near-shell's installed.  The correct is in /usr/bin/ and an older version must be in /usr/local/bin/ which was being called first.  I'm guessing it was a local npm install of near-shell not global.
