### ISSUE TITLE
[BUG] Cannot lock contract pool due to previous delete key failure

### ISSUE THREAD

**Issue by marshall-d-teach** [nearprotocol/stakewars#527]
I try to delete the access key of stakepool, but failed of network failed.

```
ubuntu@VM-0-2-ubuntu:~/stakewars$ near delete-key --accessKey 96oRvMeQJ9GgRwx7D2tKe4Tae6H9wAwBaxMHkDLjYFVx --accountId stakepool.xiaoshen.betanet
Using options: {
  accessKey: '96oRvMeQJ9GgRwx7D2tKe4Tae6H9wAwBaxMHkDLjYFVx',
  accountId: 'stakepool.xiaoshen.betanet',
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.near.org',
  contractName: undefined,
  walletUrl: 'https://wallet.betanet.near.org',
  helperUrl: 'https://helper.betanet.near.org',
  helperAccount: 'betanet',
  useLedgerKey: "44'/397'/0'/0'/1'",
  initialBalance: null
}
Deleting key = 96oRvMeQJ9GgRwx7D2tKe4Tae6H9wAwBaxMHkDLjYFVx on stakepool.xiaoshen.betanet.
^[[A^[[A^[[BError:  FetchError: request to https://rpc.betanet.near.org/ failed, reason: socket hang up
    at ClientRequest.<anonymous> (/home/ubuntu/.nvm/versions/node/v14.0.0/lib/node_modules/near-shell/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketOnEnd (_http_client.js:485:9)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1218:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

Then I tried again, but my it seems my keys are deleted. It means I cannot lock the contract pool? 
How to handle this problem?

```
ubuntu@VM-0-2-ubuntu:~/stakewars$ near delete-key --accessKey 96oRvMeQJ9GgRwx7D2tKe4Tae6H9wAwBaxMHkDLjYFVx --accountId stakepool.xiaoshen.betanet
Using options: {
  accessKey: '96oRvMeQJ9GgRwx7D2tKe4Tae6H9wAwBaxMHkDLjYFVx',
  accountId: 'stakepool.xiaoshen.betanet',
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.near.org',
  contractName: undefined,
  walletUrl: 'https://wallet.betanet.near.org',
  helperUrl: 'https://helper.betanet.near.org',
  helperAccount: 'betanet',
  useLedgerKey: "44'/397'/0'/0'/1'",
  initialBalance: null
}
Deleting key = 96oRvMeQJ9GgRwx7D2tKe4Tae6H9wAwBaxMHkDLjYFVx on stakepool.xiaoshen.betanet.
Error:  TypedError: Can not sign transactions for account stakepool.xiaoshen.betanet, no matching key pair found in Signer.
    at Account.signAndSendTransaction (/home/ubuntu/.nvm/versions/node/v14.0.0/lib/node_modules/near-shell/node_modules/near-api-js/lib/account.js:92:19)
    at async deleteAccessKey (/home/ubuntu/.nvm/versions/node/v14.0.0/lib/node_modules/near-shell/commands/delete-key.js:21:20)
    at async Object.handler (/home/ubuntu/.nvm/versions/node/v14.0.0/lib/node_modules/near-shell/utils/exit-on-error.js:37:9) {
  type: 'KeyNotFound'
}
```
I think this is the same error as #525 .
I need to create another pool in order to finish the challenge 1 steps?  oh :(

**Comment by bowenwang1996** [comment]
You can use `near keys <contract_id>` to see if the contract still has any keys.

**Comment by marshall-d-teach** [comment]
@bowenwang1996 
```
Keys for account stakepool.xiaoshen.betanet
[
  {
    public_key: 'ed25519:96oRvMeQJ9GgRwx7D2tKe4Tae6H9wAwBaxMHkDLjYFVx',
    access_key: { nonce: 4, permission: 'FullAccess' }
  },
  [length]: 1
]
```

**Comment by bowenwang1996** [comment]
Do you have access to the account? Depending on how you created the account you have might keys in the web wallet.

**Comment by jimmy3dita** [comment]
@marshall-d-teach any updates on this issue? Were you able to remove the keys? 

Alternatively, have you tried to deploy the contract using the staking pool factory? https://github.com/near/core-contracts/tree/master/staking-pool-factory

**Comment by marshall-d-teach** [comment]
@jimmy3dita , sorry for the delay. keys to stakepool.xiaoshen.betanet have been deleted locally with `near delete-key`, I cannot delete it again because of no keys. I have deployed a new pool. Looking forward to see `near shell` to handle different error perfectly. I close this issue now. Thanks!
