### ISSUE TITLE
[BUG] Near Shell error on sending low amounts

### ISSUE THREAD

**Issue by krisboit** [nearprotocol/stakewars#87]
**Describe the bug or test**
I managed to create an account from the shell, using `near account_create`, now i want to send tokens to an account.

**How to Reproduce**
1. Install near shell
2. `near login moonlet2`
2. try to use `near send moonlet2 ttt 10`

**Expected behavior OR Outcome of test**
I would expect to send tokens using `near send` command. Also if there is an error i would expect to get a clear error message. Right now i get:
```
Error:  TypeError: amt.trim is not a function
```

**Specs (please complete the following information):**
- OS: macOS
- Which cloud / on-premise: personal laptop
- CPU: i7 dual core
- RAM: 16Gb
- Disk space: 512 Gb 

**Additional context**
```
$ NODE_ENV=tatooine near login moonlet2
[WARNING] Didn't find config at /Users/krisboit/Work/projects/validator/automation/src/config, using default shell config
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Please navigate to this url and follow the instructions to log in: 
https://wallet.tatooine.nearprotocol.com/login/?title=NEAR+Shell&public_key=ed25519%3A6zMDH4fSoJJPTB9eGDdBumtzys6AJ3U3WxSK6v2Yspb3
Please enter the accountId that you logged in with:moonlet2
Logged in as moonlet2 with public key ed25519:6zMDH4fSoJJPTB9eGDdBumtzys6AJ3U3WxSK6v2Yspb3 successfully

$ NODE_ENV=tatooine near state moonlet2
[WARNING] Didn't find config at /Users/krisboit/Work/projects/validator/automation/src/config, using default shell config
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Account moonlet2
{ amount: '9999989999999963990',
  block_height: 55951,
  code_hash: '11111111111111111111111111111111',
  locked: '10043701855007018870',
  storage_paid_at: 55928,
  storage_usage: 428,
  formattedAmount: '9.99998999999996399' }

$ NODE_ENV=tatooine near state ttt
[WARNING] Didn't find config at /Users/krisboit/Work/projects/validator/automation/src/config, using default shell config
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Account ttt
{ amount: '10',
  block_height: 55954,
  code_hash: '11111111111111111111111111111111',
  locked: '0',
  storage_paid_at: 55443,
  storage_usage: 182,
  formattedAmount: '0.00000000000000001' }

$ NODE_ENV=tatooine near send moonlet2 ttt 10
[WARNING] Didn't find config at /Users/krisboit/Work/projects/validator/automation/src/config, using default shell config
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Error:  TypeError: amt.trim is not a function
    at Object.parseNearAmount (/Users/krisboit/.nvm/versions/node/v10.16.3/lib/node_modules/near-shell/node_modules/nearlib/lib/utils/format.js:29:15)
    at exports.sendMoney (/Users/krisboit/.nvm/versions/node/v10.16.3/lib/node_modules/near-shell/index.js:146:60)
    at Object.handler (/Users/krisboit/.nvm/versions/node/v10.16.3/lib/node_modules/near-shell/utils/exit-on-error.js:2:31)
    at innerArgv.then.argv (/Users/krisboit/.nvm/versions/node/v10.16.3/lib/node_modules/near-shell/node_modules/yargs/lib/command.js:238:63)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
With a higher amount it works:
```
$ NODE_ENV=tatooine near send moonlet2 ttt 1000000000000000000
[WARNING] Didn't find config at /Users/krisboit/Work/projects/validator/automation/src/config, using default shell config
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Sending 1000000000000000000 (1000000000000000000) NEAR to ttt from moonlet2
{ receipts:
   [ { id: 'DtbKFDU9dPjT3gAKQLvZcRk7xAEhtntMyLoAB5d2DAA5',
       outcome:
        { gas_burnt: 20,
          logs: [],
          receipt_ids: [],
          status: { SuccessValue: '' } },
       proof: [] } ],
  status: { SuccessValue: '' },
  transaction:
   { id: 'CJvkfQNWPdML8qZbiXGnB4ZhZN7pJwn1ikkVzvu4s4xR',
     outcome:
      { gas_burnt: 20,
        logs: [],
        receipt_ids: [ 'DtbKFDU9dPjT3gAKQLvZcRk7xAEhtntMyLoAB5d2DAA5' ],
        status:
         { SuccessReceiptId: 'DtbKFDU9dPjT3gAKQLvZcRk7xAEhtntMyLoAB5d2DAA5' } },
     proof: [] } }
```

**Screenshots Optional**

**Comment by eorituz** [comment]
I'm able to reproduce this issue with exactly the same error code.
